name: Loots
version: '${project.version}'
main: com.github.bfabri.loots.Loots
softdepend:
  - Holograms
  - HolographicDisplays
  - DecentHolograms
commands:
  loots:
    aliases:
      - "crate"
      - "cr"
